version: "3.7"
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/project
      - frontend_deps:/project/frontend/node_modules:cached
      - frontend_exts:/root/.vscode-server/extensions:cached

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/project
      - backend_deps:/project/backend/.venv:cached
      - backend_exts:/root/.vscode-server/extensions:cached

volumes:
  frontend_deps:
  frontend_exts:
  backend_deps:
  backend_exts:
