# Generated by Django 3.0.4 on 2020-03-12 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjlog_id', models.CharField(max_length=63, verbose_name='天鳳牌譜ID')),
                ('target_wind', models.PositiveSmallIntegerField(default=0, verbose_name='視点')),
                ('review_status', models.PositiveSmallIntegerField(choices=[(1, '予約中'), (2, 'レビュー中'), (3, 'レビュー完了'), (4, 'エラー終了')], default=1, verbose_name='レビューの状況')),
                ('review_result', models.TextField(blank=True, verbose_name='レビューの結果')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='予約時刻')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='終了時刻')),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー',
                'db_table': 'reviews',
            },
        ),
    ]
