# Generated by Django 3.0.4 on 2020-03-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.PositiveSmallIntegerField(choices=[(1, '予約中'), (2, 'レビュー中'), (3, 'レビュー完了'), (4, 'エラー終了')], default=1, verbose_name='レビューの状況'),
        ),
    ]
